@startuml New Secret
title How to create a new Secret

start
:input profile_key, scope_key, auth_key, password, value, Optional expire_date;/

if (params are invalid or profile_password do not match profile password?) then (yes)
    #red: error;
    stop
endif
:
let secret_key = random bytes(24)
let secret_key_hash = hash with sha356(secret_key)
;
:
let system_key = generate system key with (secret_key_hash)
;
:
let nonce = derive with (secret_key_hash, system_key)
;
:
Create a Secret with
    key: encode_b64(secret_key),
    owner_profile_key: profile_key,
    owner_scope_key: scope_key,
    value: encode_b64(value),
    created: now.to_string(),
    expirable: expire_date is Some,
    expire: expire_date
;
:
Cipher the secret with 
    Key: auth_key, 
    nonce: nonce, 
    aead: system_key
as secret_secure
;
:
Create an SecretContainer with
    key: secret_key,
    secret_secure: secret_secure
as secret_container
;
:
Add the scope_container to the store
;
end
@enduml